config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end

  

  devise_for :users, :controllers => { registrations: 'users/registrations' }
  resources :users

  resources :likes, only: [:create, :destroy]
  root "users#new"
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: :post_id }
  belongs_to :user
  belongs_to :post
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(like_params)
    if @like.save
      redirect_to @like.post
    else
      flash[:notice] = @like.errors.full_messages.to_sentence
      redirect_to @like.post
    end
  end

  def destroy
    @like = current_user.likes.find(params[:id])
    post = @like.post
    @like.destroy
    redirect_to post
  end

  private

  def like_params
    params.require(:like).permit(:post_id)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.erb
<% like = current_user.likes.find_by(post: @post) %>
<% if like.nil? %>
  <form action="/likes" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="like[post_id]" value="<%= @post.id %>">
    <input type="submit" value="Like">
  </form>
<% else %>
  <form action="<%= like_path(like) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Unlike">
  </form>
<% end %>